# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# Updated workflow name to reflect the NEW app target
# Under is an example procedure that worked previously in a deployment on Azure. 

"
name: Build and deploy container app to Azure Web App - <Your-Unique-New-App-Name>

on:
  push:
    branches:
      - main # Triggers on push to the main branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: 'ubuntu-latest' # Specifies the runner environment

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2 # Checks out your code so the workflow can access it

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 # Sets up Docker build capabilities

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: https://placeholder.azurecr.io/ # Your ACR URL
        username: [put actual values here]
        password: [put actual values here]

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true # Tells the action to push the image after building
        # CORRECTED TAGS FORMAT: Uses registry/image:tag (all lowercase)
        tags: placeholder.azurecr.io/placeholderimage:${{ github.sha }}
        file: ./Dockerfile # Specifies the path to your Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build # Ensures the build job completes successfully before deploying
    environment:
      name: 'production' # Defines the deployment environment (optional)
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }} # Sets the environment URL after deployment

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp # Step ID for referencing outputs
      uses: azure/webapps-deploy@v2
      with:
        # IMPORTANT: Use your NEW App Service name here!
        app-name: 'placeholder'
        slot-name: 'production' # Deploys to the production slot
        # Using publish profile for authentication to Azure App Service
        publish-profile: ${{ put actual value here }}
        # CORRECTED IMAGES FORMAT: Must match the tag built in the previous job
        images: 'placeholder.azurecr.io/placeholderimage:${{ github.sha }}'
"